### ISSUE TITLE
Missing column 'campains' in tt_content

### ISSUE THREAD

**Issue by mpflaum** [slavlee/advertising#1]
SQL error: 'Unknown column 'campaigns' in 'field list'

**Comment by slavlee** [comment]
Hi mpflaum,

unfortunately I can't reproduce this problem. I just reinstalled the extension in a new environment and I don't get this kind of error. 

Can you tell me, when this error happens? And what version do you have?

Thanks.

**Comment by slavlee** [comment]
Nevermind, I found the problem and fixed it in the new version: 0.17.23.
